### PR TITLE
Split rules into individual ones.

### PR DESCRIPTION
**Pull request by selaux**

### CODE REVIEW

**Comment by mlucool** [comment]
Hi,

Can we add in how to turn on the new rule in the README? i.e. ``` "filenames/match-exported": [2]```

Also it has an unintended effect by splitting it.
Rules (basically start with a lowercase letter):
````
    "filenames/match-regex": [2, "^([a-z][-a-zA-Z_0-9]+)|([a-zA-Z][-a-zA-Z_0-9]+_spec)$"],
    "filenames/match-exported": [2]
```
The split into two rules has a bad effect:
Bar.js
```
export default function Bar() {
    return 'hello';
}
```
```
tasks/Bar.js
  1:1  error  Filename 'Bar.js' does not match the naming convention  filenames/match-regex
```

Since the rules are independent the first rule fails while the second works. Ideally I'd like to have the match-exported rule override the match-regex rule as I think it was originally.

The index.js rule does work now!

**Comment by selaux** [comment]
The readme is updated in this branch. What we could do to somehow reintroduce the full functionality is to add a flag to the `match-regex` rule, called `ignore-exporting` that allows you to toggle whether you want this rule to apply to exporting files.

**Comment by mlucool** [comment]
I see the README is updated, but I was suggesting to have code to copy/paste to enable the rule.

I like that idea to ignore exporting!

**Comment by selaux** [comment]
Please have another try.

**Comment by mlucool** [comment]
Small bug it looks like:
```+        ignoreExporting = context.options[0] ? context.options[0] : false;```
This should is the same arg as the RegExp so its always enabled. In the enable case it does work as expected

**Comment by selaux** [comment]
Whoops, shit happens ... sometimes. Should be fixed now.

**Comment by mlucool** [comment]
Looks good now! Looking forward to the release

**Comment by gajus** [comment]
@selaux Can this be merged?

**Pull request merged**
